[package]
name = "belugasnooze"
version = "0.0.1"
edition = "2021"
authors = ["Jack Wills <email@mrjackwills.com>"]
description = "belugasnooze pi client"

[target.'cfg(not(target_arch = "x86_64"))'.dependencies]
openssl = { version = '0.10', features = ["vendored"] }

[dependencies]
anyhow = "1.0.55"
blinkt = "0.6.0"
dotenv = "0.15.0"
figlet-rs = "0.1.3"
futures-util = "0.3.21"
rand = "0.8.5"
reqwest = {version = "0.11.9", features=["json", "native-tls"]}
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0"
simple-signal = "1.1.1"
sqlx = { version = "0.5", default-features = false, features = [ "runtime-tokio-rustls", "sqlite", "macros"] }
thiserror = "1.0.30"
time = {version="0.3.7", features=["local-offset", "macros"]}
time-tz = "1.0.1"
tokio = {version ="1", features=["full"]}
tokio-tungstenite={version= "0.17.1", features = ["native-tls"]}
tracing = "0.1.32"
tracing-subscriber = "0.3.9"
url = "2.2.2"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip=true
debug = false
