[package]
name = "belugasnooze"
version = "0.1.9"
edition = "2021"
authors = ["Jack Wills <email@mrjackwills.com>"]
description = "belugasnooze - A pi based wake up light sunrise alarm clock"

[dependencies]
blinkt = "0.7"
dotenvy = "0.15"
figlet-rs = "0.1"
futures-util = "0.3"
openssl = { version = '0.10', features = ["vendored"] }
reqwest = {version = "0.11", features=["json", "native-tls"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple-signal = "1.1"
sqlx = { version = "0.6", default-features = false, features = [ "runtime-tokio-rustls", "sqlite", "macros"] }
thiserror = "1.0"
time = {version="0.3", features=["local-offset", "macros"]}
time-tz = "1.0"
tokio = {version ="1.22", features=["full"]}
tokio-tungstenite={version= "0.17", features = ["native-tls"]}
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2.3"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip=true
debug = false
