version: "3.8"
services:
  belugasnooze_pi:
    image: belugasnooze_pi:9.1.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_UID=${DOCKER_UID}
        - DOCKER_GUID=${DOCKER_GUID}
        - DOCKER_TIME_CONT=${DOCKER_TIME_CONT}
        - DOCKER_TIME_CITY=${DOCKER_TIME_CITY}
    container_name: belugasnooze_pi
    env_file: .env
    volumes:
      - /ramdrive/ip.addr:/ip_address/ip.addr:ro
      - /sys:/sys
      - $HOME/belugasnooze/alarms:/alarms
      - $HOME/belugasnooze/logs:/logs
    cap_drop:
      - all
    group_add:
      - ${DOCKER_GPIO}
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    networks:
      - belugasnooze-net
    deploy:
      resources:
        limits:
          memory: 96M
networks:
  belugasnooze-net:
    name: belugasnooze-net
