const Africa = 'Africa';
const America = 'America';
const Antarctica = 'Antarctica';
const Arctic = 'Arctic';
const Asia = 'Asia';
const Atlantic = 'Atlantic';
const Australia = 'Australia';
const Europe = 'Europe';
const Indian = 'Indian';
const Pacific = 'Pacific';

const _parents = [];

for (const i of [ Africa, America, Antarctica, Arctic, Asia, Atlantic, Australia, Europe, Indian, Pacific ]) _parents.push(i);

export const parents: Readonly<Array<string>> = [ ..._parents ];

const africaZones = [
	'Abidjan',
	'Accra',
	'Addis_Ababa',
	'Algiers',
	'Asmera',
	'Bamako',
	'Bangui',
	'Banjul',
	'Bissau',
	'Blantyre',
	'Brazzaville',
	'Bujumbura',
	'Cairo',
	'Casablanca',
	'Ceuta',
	'Conakry',
	'Dakar',
	'Dar_es_Salaam',
	'Djibouti',
	'Douala',
	'El_Aaiun',
	'Freetown',
	'Gaborone',
	'Harare',
	'Johannesburg',
	'Juba',
	'Kampala',
	'Khartoum',
	'Kigali',
	'Kinshasa',
	'Lagos',
	'Libreville',
	'Lome',
	'Luanda',
	'Lubumbashi',
	'Lusaka',
	'Malabo',
	'Maputo',
	'Maseru',
	'Mbabane',
	'Mogadishu',
	'Monrovia',
	'Nairobi',
	'Ndjamena',
	'Niamey',
	'Nouakchott',
	'Ouagadougou',
	'Porto-Novo',
	'Sao_Tome',
	'Tripoli',
	'Tunis',
	'Windhoek',
];

const americaZones = [
	'Anchorage',
	'Anguilla',
	'Antigua',
	'Araguaina',
	'Argentina/La_Rioja',
	'Argentina/Rio_Gallegos',
	'Argentina/Salta',
	'Argentina/San_Juan',
	'Argentina/San_Luis',
	'Argentina/Tucuman',
	'Argentina/Ushuaia',
	'Aruba',
	'Asuncion',
	'Bahia',
	'Bahia_Banderas',
	'Barbados',
	'Belem',
	'Belize',
	'Blanc-Sablon',
	'Boa_Vista',
	'Bogota',
	'Boise',
	'Buenos_Aires',
	'Cambridge_Bay',
	'Campo_Grande',
	'Cancun',
	'Caracas',
	'Catamarca',
	'Cayenne',
	'Cayman',
	'Chicago',
	'Chihuahua',
	'Coral_Harbour',
	'Cordoba',
	'Costa_Rica',
	'Creston',
	'Cuiaba',
	'Curacao',
	'Danmarkshavn',
	'Dawson',
	'Dawson_Creek',
	'Denver',
	'Detroit',
	'Dominica',
	'Edmonton',
	'Eirunepe',
	'El_Salvador',
	'Fortaleza',
	'Glace_Bay',
	'Godthab',
	'Goose_Bay',
	'Grand_Turk',
	'Grenada',
	'Guadeloupe',
	'Guatemala',
	'Guayaquil',
	'Guyana',
	'Halifax',
	'Havana',
	'Hermosillo',
	'Indiana/Knox',
	'Indiana/Marengo',
	'Indiana/Petersburg',
	'Indiana/Tell_City',
	'Indiana/Vevay',
	'Indiana/Vincennes',
	'Indiana/Winamac',
	'Indianapolis',
	'Inuvik',
	'Iqaluit',
	'Jamaica',
	'Jujuy',
	'Juneau',
	'Kentucky/Monticello',
	'Kralendijk',
	'La_Paz',
	'Lima',
	'Los_Angeles',
	'Louisville',
	'Lower_Princes',
	'Maceio',
	'Managua',
	'Manaus',
	'Marigot',
	'Martinique',
	'Matamoros',
	'Mazatlan',
	'Mendoza',
	'Menominee',
	'Merida',
	'Mexico_City',
	'Moncton',
	'Monterrey',
	'Montevideo',
	'Montreal',
	'Montserrat',
	'Nassau',
	'New_York',
	'Nipigon',
	'Nome',
	'Noronha',
	'North_Dakota/Beulah',
	'North_Dakota/Center',
	'North_Dakota/New_Salem',
	'Ojinaga',
	'Panama',
	'Pangnirtung',
	'Paramaribo',
	'Phoenix',
	'Port_of_Spain',
	'Port-au-Prince',
	'Porto_Velho',
	'Puerto_Rico',
	'Rainy_River',
	'Rankin_Inlet',
	'Recife',
	'Regina',
	'Resolute',
	'Rio_Branco',
	'Santa_Isabel',
	'Santarem',
	'Santiago',
	'Santo_Domingo',
	'Sao_Paulo',
	'Scoresbysund',
	'Sitka',
	'St_Barthelemy',
	'St_Johns',
	'St_Kitts',
	'St_Lucia',
	'St_Thomas',
	'St_Vincent',
	'Swift_Current',
	'Tegucigalpa',
	'Thule',
	'Thunder_Bay',
	'Tijuana',
	'Toronto',
	'Tortola',
	'Vancouver',
	'Whitehorse',
	'Winnipeg',
	'Yakutat',
	'Yellowknife',
];

const antarcticaZones = [
	'Casey',
	'Davis',
	'DumontDUrville',
	'Macquarie',
	'Mawson',
	'McMurdo',
	'Palmer',
	'Rothera',
	'Syowa',
	'Vostok',
	'Longyearbyen',
];

const asiaZones = [
	'Aden',
	'Almaty',
	'Amman',
	'Anadyr',
	'Aqtau',
	'Aqtobe',
	'Ashgabat',
	'Baghdad',
	'Bahrain',
	'Baku',
	'Bangkok',
	'Beirut',
	'Bishkek',
	'Brunei',
	'Chita',
	'Choibalsan',
	'Colombo',
	'Damascus',
	'Dhaka',
	'Dili',
	'Dubai',
	'Dushanbe',
	'Hong_Kong',
	'Hovd',
	'Irkutsk',
	'Jakarta',
	'Jayapura',
	'Jerusalem',
	'Kabul',
	'Kamchatka',
	'Karachi',
	'Kathmandu',
	'Khandyga',
	'Kolkata',
	'Krasnoyarsk',
	'Kuala_Lumpur',
	'Kuching',
	'Kuwait',
	'Macau',
	'Magadan',
	'Makassar',
	'Manila',
	'Muscat',
	'Nicosia',
	'Novokuznetsk',
	'Novosibirsk',
	'Omsk',
	'Oral',
	'Phnom_Penh',
	'Pontianak',
	'Pyongyang',
	'Qatar',
	'Qyzylorda',
	'Rangoon',
	'Riyadh',
	'Saigon',
	'Sakhalin',
	'Samarkand',
	'Seoul',
	'Shanghai',
	'Singapore',
	'Srednekolymsk',
	'Taipei',
	'Tashkent',
	'Tbilisi',
	'Tehran',
	'Thimphu',
	'Tokyo',
	'Ulaanbaatar',
	'Urumqi',
	'Ust-Nera',
	'Vientiane',
	'Vladivostok',
	'Yakutsk',
	'Yekaterinburg',
	'Yerevan',
];

const atlanticZones = [
	'Azores',
	'Bermuda',
	'Canary',
	'Cape_Verde',
	'Faeroe',
	'Madeira',
	'Reykjavik',
	'South_Georgia',
	'St_Helena',
	'Stanley',
];

const australiaZones = [
	'Adelaide',
	'Brisbane',
	'Broken_Hill',
	'Currie',
	'Darwin',
	'Hobart',
	'Lindeman',
	'Melbourne',
	'Perth',
	'Sydney',
];

const europeZones = [
	'Amsterdam',
	'Andorra',
	'Astrakhan',
	'Athens',
	'Belgrade',
	'Berlin',
	'Bratislava',
	'Brussels',
	'Bucharest',
	'Budapest',
	'Busingen',
	'Chisinau',
	'Copenhagen',
	'Dublin',
	'Gibraltar',
	'Guernsey',
	'Helsinki',
	'Isle_of_Man',
	'Istanbul',
	'Jersey',
	'Kaliningrad',
	'Kiev',
	'Kirov',
	'Lisbon',
	'Ljubljana',
	'London',
	'Luxembourg',
	'Madrid',
	'Malta',
	'Mariehamn',
	'Minsk',
	'Monaco',
	'Moscow',
	'Nicosia',
	'Oslo',
	'Paris',
	'Podgorica',
	'Prague',
	'Riga',
	'Rome',
	'Samara',
	'San_Marino',
	'Sarajevo',
	'Simferopol',
	'Skopje',
	'Sofia',
	'Stockholm',
	'Tallinn',
	'Tirane',
	'Ulyanovs',
	'Uzhgorod',
	'Vaduz',
	'Vatican',
	'Vienna',
	'Vilnius',
	'Volgograd',
	'Warsaw',
	'Zagreb',
	'Zaporozhye',
	'Zurich',
];

const indianZones = [
	'Antananarivo',
	'Chagos',
	'Christmas',
	'Cocos',
	'Comoro',
	'Kerguelen',
	'Mahe',
	'Maldives',
	'Mauritius',
	'Mayotte',
	'Reunion',
];

const pacificZones = [
	'Apia',
	'Auckland',
	'Efate',
	'Enderbury',
	'Fakaofo',
	'Fiji',
	'Funafuti',
	'Galapagos',
	'Guadalcanal',
	'Guam',
	'Honolulu',
	'Johnston',
	'Kosrae',
	'Kwajalein',
	'Majuro',
	'Midway',
	'Nauru',
	'Niue',
	'Noumea',
	'Pago_Pago',
	'Palau',
	'Ponape',
	'Port_Moresby',
	'Rarotonga',
	'Saipan',
	'Tahiti',
	'Tarawa',
	'Tongatapu',
	'Truk',
	'Wake',
	'Wallis',
];
const _zones = [];

for (const i of africaZones) _zones.push(`${Africa}/${i}`);
for (const i of americaZones) _zones.push(`${America}/${i}`);
for (const i of antarcticaZones) _zones.push(`${Antarctica}/${i}`);
for (const i of asiaZones) _zones.push(`${Asia}/${i}`);
for (const i of atlanticZones) _zones.push(`${Atlantic}/${i}`);
for (const i of australiaZones) _zones.push(`${Australia}/${i}`);
for (const i of europeZones) _zones.push(`${Europe}/${i}`);
for (const i of indianZones) _zones.push(`${Indian}/${i}`);
for (const i of pacificZones) _zones.push(`${Pacific}/${i}`);

export const TZ: Readonly<Array<string>> = [ ..._zones ];
