name: Release CI
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: build arm-unknown-linux-musleabihf 
        run: cross build --target arm-unknown-linux-musleabihf --release

      - name: compress armv6 binary
        run: tar -C target/arm-unknown-linux-musleabihf/release -czf ./belugasnooze_linux_armv6.tar.gz belugasnooze

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body_path: ".github/release-body.md"
          draft: false
          files: |
             belugasnooze_linux_armv6.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}