name: Release CI
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      # Build for linux armv6, aka 32 bit pi zero w
      - name: build release armv6
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target:  arm-unknown-linux-musleabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target arm-unknown-linux-musleabihf --release
      - name: compress armv6 binary
        run: tar -C target/arm-unknown-linux-musleabihf/release -czf ./belugasnooze_linux_armv6.tar.gz belugasnooze

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body_path: ".github/release-body.md"
          draft: false
          files: |
             belugasnooze_linux_armv6.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}